# Generated by Django 4.1.7 on 2023-04-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_pool_restaurant_remove_employee_user_employee_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='img',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
