# Generated by Django 4.1.7 on 2023-04-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_employee_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolemployeerelation',
            name='hourly_wage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='poolemployeerelation',
            name='start_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='restaurantemployeerelation',
            name='hourly_wage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restaurantemployeerelation',
            name='start_Date',
            field=models.DateField(null=True),
        ),
    ]
